### ISSUE TITLE
`$data_root/metadata/ModelClassMapping.csv` missing

### ISSUE THREAD

**Issue by mgarbade** [shurans/SUNCGtoolbox#11]
I'm trying to extract label files using 

    scn2img house.json camera_pose.cam  -capture_category_images -categories  path/to/SUNCGtoolbox/metadata/ModelCategoryMapping.csv

but it outputs label files with labels ranging withing [0:2543] instead of [0:36] as in NYU11 or even [0:11].
I assume I need the file `ModelClassMapping.csv` as mentioned in the README. However this file doesn't seem to be part of the repository. 
Can you please provide me this file or else tell me how to map the  [0:2543]  categories to the [0:36] labels of NYU ?

Thanks in advance

**Comment by shurans** [comment]
@mgarbade You can find the file in the ./metadata/ModelCategoryMapping.csv

https://github.com/shurans/SUNCGtoolbox/blob/master/metadata/ModelCategoryMapping.csv
