### ISSUE TITLE
Run SUNCGtoolbox in remote X sessions

### ISSUE THREAD

**Issue by Emrys-Lee** [shurans/SUNCGtoolbox#12]
Hi, Is it possible to run SUNCGtoolbox and do rendering on a remote Linux system? I connect to the system using SSH with Xming, compiled the project successfully with OpenGL, yet when running the program fails with the following error:

> freeglut (scn2cam):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  4 (X_DestroyWindow)
  Resource id in failed request:  0x0
  Serial number of failed request:  13
  Current serial number in output stream:  16

It is said to be related to a freeglut [bug](https://sourceforge.net/p/freeglut/bugs/123/)
I'm not sure if anyone already has a solution.

**Comment by shurans** [comment]
You can try to use compile with OSMesa and run the program with  -mesa. It will use CPU rendering and do not require OpenGL.

**Comment by Emrys-Lee** [comment]
Thank you. I'll try.
