### ISSUE TITLE
Cannot locate room.zip file in the dataset

### ISSUE THREAD

**Issue by atinesh-s** [shurans/SUNCGtoolbox#15]
I have downloaded the dataset and extracted the `.zip` files as instructed in the documentation page. The documentation page mentions `room.zip` file as we can see [here](https://s22.postimg.cc/6e73l43mp/data_root.png), But I cannot see that file in the downloaded dataset.

Downloaded dataset files that I have are 

`house.zip`,  `navgrid_10.zip`,  `object_vox.zip`, ` object.zip`,  `stats.zip`,  `texture.zip`,  `wall.zip`

One more issue I am facing is on running the following command

`gaps/bin/x86_64/scnview house.json -v `

from the directory `data_root/house/<sceneid>/` I get 3D view of room without the walls as we can see from this [image](https://s22.postimg.cc/u6gewpxyp/room.png) where compilation is done with OpenGL. How can I resolve these issues.

**Comment by shurans** [comment]
If you are running with default arguments, latest release with no room architectures will be downloaded. Run ./download_suncg.py -v v1 -t room to download room architectures.

**Comment by mpkuse** [comment]
I downloaded the room.zip. I viewed the obj files in it with meshlab, they seem to be just planes with texture on it. 

How can I get the full 3D scenes (with walls) as you have shown on your website?

**Comment by atinesh-s** [comment]
Hello mpkuse please see shurans comment
