### ISSUE TITLE
Rendering yields 0 maps

### ISSUE THREAD

**Issue by lynetcha** [shurans/SUNCGtoolbox#2]
I followed the instructions to render images from OpenGL, the color images look fine, but several maps are simply 0 (depth, kinect, material, ...). Is there anything I could be missing?

**Comment by shurans** [comment]
@lynetcha , do you mind to provide more information on the issue? What exact command you run, which house file, and what's your camera file? For the output depth files, did you try to read and visualize the pixel values? They may looks black but their value may not be 0.

**Comment by lynetcha** [comment]
You are right, I just read the values, they are simply very low, but non-zero. Thanks! One more question, does the code base provide a way to get the 3D Point Clouds from the depth maps? This would be helpful to visualize the kinect point cloud for instance.

**Comment by shurans** [comment]
The depth is saved in 16 png unit is millimeter. 
Following function (Matlab) can be used to convert depth to point cloud x,y,z


function [points3d]=read_3d_pts(depthInpaint,K)
    % K is [fx 0 cx; 0 fy cy; 0 0 1];  
    % depthInpaint depthmap in meters
    % points3d will point could x,y,z in meter
    cx = K(1,3); cy = K(2,3);  
    fx = K(1,1); fy = K(2,2); 
    invalid = depthInpaint==0;

    %3D points
    depthInpaintsize = size(depthInpaint);
    [x,y] = meshgrid(1:depthInpaintsize(2), 1:depthInpaintsize(1));   
    x3 = (x-cx).*depthInpaint*1/fx;  
    y3 = (y-cy).*depthInpaint*1/fy;  
    z3 = depthInpaint;  
    points3d = [x3(:) y3(:) z3(:)];
    points3d(invalid(:),:) =NaN;
end

**Comment by lynetcha** [comment]
Which K do you use?

**Comment by lynetcha** [comment]
Is it 
693.7447         0  360.4319
0  693.7447  264.7500
0         0    1.0000
?

**Comment by lynetcha** [comment]
I used that matrix and the results seem reasonable (I got it from the SUNRGBD metadata). Thanks!
