### ISSUE TITLE
Dataset information in time?

### ISSUE THREAD

**Issue by chibai** [shurans/SUNCGtoolbox#25]
I'm new in this area, and I'm tring to do some research on SUNCG dataset.
According README.md of this project, there're 4 directories in this root_directory, they are house, room, object, texture.
But when I download the Dataset about 3 days ago.  I found there're a lot of directories over 4, they are house, navgrid_10, object, object_vox, stats, texture, wall.  And I can not find the directory of room.
Is there any problem about my downloading, or is there any place I can find the full documentation (update in time) about the dataset.
It is ez to understand the dataset for a sophiscated researcher on this area, but it's a little bit unfriendly for freshers like me

**Comment by shurans** [comment]
@chibai If you are running the download script with default arguments, latest release with no room architectures will be downloaded. Run ./download_suncg.py -v v1 -t room to download room architectures.

**Comment by chibai** [comment]
Thank you for your instruction
