### ISSUE TITLE
How to get tight bounding box for the room

### ISSUE THREAD

**Issue by xcyan** [shurans/SUNCGtoolbox#4]
As far as I can see, in the json file, the tight box is available for objects and levels but not for individual rooms. 

For example, the json file with house id: 0004d52d1aeeb8ae6de39d6bd993e992.

**Comment by shurans** [comment]
@xcyan Currently the JSON data doesn't include bounding box for an individual room, but I imagine it is not hard to compute them - after you load the all the room meshes including wall, floor, ceiling, you can compute the bounding box that encompasses all the vertices.

**Comment by xcyan** [comment]
@shurans Got it. Thanks!

**Comment by xcyan** [comment]
@shurans While preprocessing, I found nan value in some (roughly 1%) of the room meshes.

For example, this one in the dataset:
room/0114a23a28a7df6b54d0ff628bf3e770/fr_0rm_1w.obj

**Comment by shurans** [comment]
Hi @xcyan 
You can simply ignore all the walls that have NaN vertice - they are invalid walls in the original scene generation.
